/* Generated By:JavaCC: Do not edit this line. genericLex1Constants.java */
package h2PVisitors.Parser;

public interface genericLex1Constants {

  int EOF = 0;
  int MAKE_OUT = 1;
  int DIGIT = 2;
  int LETTER = 3;
  int WEIRD = 4;
  int DELIMETER = 5;
  int WEIRDTOK = 6;
  int LABELTOK = 7;
  int ALL_ELSE = 8;

  int DEFAULT = 0;
  int MAKE_OUT_STATE = 1;

  String[] tokenImage = {
    "<EOF>",
    "\"make_out\"",
    "<DIGIT>",
    "<LETTER>",
    "<WEIRD>",
    "\"\\n\"",
    "<WEIRDTOK>",
    "\":\"",
    "<ALL_ELSE>",
  };

}
