/* Generated By:JavaCC: Do not edit this line. UMLLtl1Constants.java */
package h2PVisitors.Parser;

public interface UMLLtl1Constants {

  int EOF = 0;
  int OR = 6;
  int AND = 7;
  int NOT = 8;
  int IMP = 9;
  int COMPARE_OP = 10;
  int IN = 11;
  int PLUS = 12;
  int MINUS = 13;
  int TIMES = 14;
  int SEMICOLON = 15;
  int LPARENS = 16;
  int RPARENS = 17;
  int PERIOD = 18;
  int COMMA = 19;
  int SLASH = 20;
  int SENT = 21;
  int UNOP = 22;
  int EQV = 23;
  int DIGIT = 24;
  int LETTER = 25;
  int NUM = 26;
  int ID = 27;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\f\"",
    "\"|\"",
    "\"&\"",
    "\"~\"",
    "\"->\"",
    "<COMPARE_OP>",
    "\"in\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\".\"",
    "\",\"",
    "\"/\"",
    "\"sent\"",
    "<UNOP>",
    "\"<->\"",
    "<DIGIT>",
    "<LETTER>",
    "<NUM>",
    "<ID>",
  };

}
