/* Generated By:JavaCC: Do not edit this line. genericLex1Constants.java */
package backend.h2PParser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface genericLex1Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MAKE_OUT = 1;
  /** RegularExpression Id. */
  int DIGIT = 2;
  /** RegularExpression Id. */
  int LETTER = 3;
  /** RegularExpression Id. */
  int WEIRD = 4;
  /** RegularExpression Id. */
  int DELIMETER = 5;
  /** RegularExpression Id. */
  int WEIRDTOK = 6;
  /** RegularExpression Id. */
  int LABELTOK = 7;
  /** RegularExpression Id. */
  int ALL_ELSE = 8;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int MAKE_OUT_STATE = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"make_out\"",
    "<DIGIT>",
    "<LETTER>",
    "<WEIRD>",
    "\"\\n\"",
    "<WEIRDTOK>",
    "\":\"",
    "<ALL_ELSE>",
  };

}
