/* Generated By:JavaCC: Do not edit this line. UMLExprConstants.java */
package backend.h2PParser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface UMLExprConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int OR = 6;
  /** RegularExpression Id. */
  int AND = 7;
  /** RegularExpression Id. */
  int NOT = 8;
  /** RegularExpression Id. */
  int IMP = 9;
  /** RegularExpression Id. */
  int COMPARE_OP = 10;
  /** RegularExpression Id. */
  int EQUALITY_OP = 11;
  /** RegularExpression Id. */
  int ASSGNOP = 12;
  /** RegularExpression Id. */
  int IN = 13;
  /** RegularExpression Id. */
  int WHEN = 14;
  /** RegularExpression Id. */
  int SENT = 15;
  /** RegularExpression Id. */
  int PLUS = 16;
  /** RegularExpression Id. */
  int MINUS = 17;
  /** RegularExpression Id. */
  int TIMES = 18;
  /** RegularExpression Id. */
  int SEMICOLON = 19;
  /** RegularExpression Id. */
  int LPARENS = 20;
  /** RegularExpression Id. */
  int RPARENS = 21;
  /** RegularExpression Id. */
  int PERIOD = 22;
  /** RegularExpression Id. */
  int COMMA = 23;
  /** RegularExpression Id. */
  int SLASH = 24;
  /** RegularExpression Id. */
  int LBRACKET = 25;
  /** RegularExpression Id. */
  int RBRACKET = 26;
  /** RegularExpression Id. */
  int CONSTANT = 27;
  /** RegularExpression Id. */
  int DIGIT = 28;
  /** RegularExpression Id. */
  int LETTER = 29;
  /** RegularExpression Id. */
  int NUM = 30;
  /** RegularExpression Id. */
  int TRUTH = 31;
  /** RegularExpression Id. */
  int ID = 32;
  /** RegularExpression Id. */
  int FULLID = 33;
  /** RegularExpression Id. */
  int UNOP = 34;
  /** RegularExpression Id. */
  int EQV = 35;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\f\"",
    "<OR>",
    "<AND>",
    "<NOT>",
    "\"->\"",
    "<COMPARE_OP>",
    "<EQUALITY_OP>",
    "<ASSGNOP>",
    "\"in\"",
    "\"when\"",
    "\"sent\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\".\"",
    "\",\"",
    "\"/\"",
    "\"[\"",
    "\"]\"",
    "<CONSTANT>",
    "<DIGIT>",
    "<LETTER>",
    "<NUM>",
    "<TRUTH>",
    "<ID>",
    "<FULLID>",
    "<UNOP>",
    "\"<->\"",
  };

}
