/* Generated By:JavaCC: Do not edit this line. UMLExpr1Constants.java */
package h2PVisitors.Parser;

public interface UMLExpr1Constants {

  int EOF = 0;
  int OR = 6;
  int AND = 7;
  int NOT = 8;
  int IMP = 9;
  int COMPARE_OP = 10;
  int ASSGNOP = 11;
  int IN = 12;
  int WHEN = 13;
  int SENT = 14;
  int PLUS = 15;
  int MINUS = 16;
  int TIMES = 17;
  int SEMICOLON = 18;
  int LPARENS = 19;
  int RPARENS = 20;
  int PERIOD = 21;
  int COMMA = 22;
  int SLASH = 23;
  int LBRACKET = 24;
  int RBRACKET = 25;
  int CONSTANT = 26;
  int DIGIT = 27;
  int LETTER = 28;
  int NUM = 29;
  int ID = 30;
  int UNOP = 31;
  int EQV = 32;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\f\"",
    "\"|\"",
    "\"&\"",
    "\"~\"",
    "\"->\"",
    "<COMPARE_OP>",
    "\":=\"",
    "\"in\"",
    "\"when\"",
    "\"sent\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\".\"",
    "\",\"",
    "\"/\"",
    "\"[\"",
    "\"]\"",
    "<CONSTANT>",
    "<DIGIT>",
    "<LETTER>",
    "<NUM>",
    "<ID>",
    "<UNOP>",
    "\"<->\"",
  };

}
