/* Generated By:JavaCC: Do not edit this line. UMLParser1Constants.java */
package h2PVisitors.Parser;

public interface UMLParser1Constants {

  int EOF = 0;
  int LCURLY = 6;
  int RCURLY = 7;
  int LBRACKET = 8;
  int RBRACKET = 9;
  int DQUOTE = 10;
  int FORMALIZE = 11;
  int AS = 12;
  int SMV = 13;
  int PROMELA = 14;
  int ALLOY = 15;
  int VHDL = 16;
  int MODEL = 17;
  int DRIVERFILE = 18;
  int CLASS = 19;
  int ASSOCIATION = 20;
  int AGGREGATION = 21;
  int AGSUBCONST = 22;
  int ORDCONST = 23;
  int ADORNS = 24;
  int GENERALIZATION = 25;
  int SIGNAL = 26;
  int CSTATE = 27;
  int STATE = 28;
  int TRANS = 29;
  int TO = 30;
  int ACTION = 31;
  int CCSTATE = 32;
  int INIT = 33;
  int JOIN = 34;
  int FROM = 35;
  int HISTORY = 36;
  int INSTVAR = 37;
  int SUPER = 38;
  int SUB = 39;
  int WHOLE = 40;
  int PART = 41;
  int NEW = 42;
  int SEND = 43;
  int WHEN = 44;
  int PRINT = 45;
  int INVARIANT = 46;
  int INVTYPENAME = 47;
  int AND = 48;
  int NOT = 49;
  int OR = 50;
  int COMPARE_OP = 51;
  int IN = 52;
  int ASSIGNOP = 53;
  int PLUS = 54;
  int MINUS = 55;
  int TIMES = 56;
  int SEMICOLON = 57;
  int LPARENS = 58;
  int RPARENS = 59;
  int PERIOD = 60;
  int COMMA = 61;
  int CONSTANT = 62;
  int DIGIT = 63;
  int LETTER = 64;
  int NUM = 65;
  int ID = 66;
  int ENDQUOTE = 67;
  int SLASH = 68;
  int CARET = 69;
  int MINIEXPRESSION = 70;
  int EXPRESSION = 71;
  int INVARIANTEXPRESSION = 72;
  int PRINTEXPRESSION = 73;

  int IN_EXPRESSION_GRAMMAR = 0;
  int DEFAULT = 1;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\f\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"\\\"\"",
    "\"Formalize\"",
    "\"as\"",
    "\"smv\"",
    "\"promela\"",
    "\"alloy\"",
    "\"vhdl\"",
    "\"Model\"",
    "\"DriverFile\"",
    "\"Class\"",
    "\"Association\"",
    "\"Aggregation\"",
    "\"Aggregation-Subclass-Constraint\"",
    "\"Ordered-Constraint\"",
    "\"adorns\"",
    "\"Generalization\"",
    "\"Signal\"",
    "\"CompositeState\"",
    "\"State\"",
    "\"Transition\"",
    "\"to\"",
    "\"Action\"",
    "<CCSTATE>",
    "\"Initial\"",
    "\"Join\"",
    "\"from\"",
    "\"History\"",
    "\"InstanceVar\"",
    "\"super\"",
    "\"sub\"",
    "\"Whole\"",
    "\"Part\"",
    "\"new\"",
    "\"send\"",
    "\"when\"",
    "\"print\"",
    "\"Invariant\"",
    "\"timeinvar\"",
    "\"&\"",
    "\"~\"",
    "\"|\"",
    "<COMPARE_OP>",
    "\"in\"",
    "\":=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\".\"",
    "\",\"",
    "<CONSTANT>",
    "<DIGIT>",
    "<LETTER>",
    "<NUM>",
    "<ID>",
    "\"\\\"\"",
    "\"/\"",
    "\"^\"",
    "<MINIEXPRESSION>",
    "<EXPRESSION>",
    "<INVARIANTEXPRESSION>",
    "<PRINTEXPRESSION>",
  };

}
